import React from 'react';
export const metadata = {
  title: "Stats Page",
  description: "Generated by create next app",
};
const InastallationPage = () => {
  return (
    <div className='w-[1600] mx-auto'>
      <h2 className='text-black'>Inastallation page</h2>
    </div>
  );
};

export default InastallationPage;