import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import themes from './../../node_modules/daisyui/theme/object.d';
import Navbar from "@/componants/shared/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        {children}
      <h2 className="bg-purple-500 text-center py-7 w-[1600] mx-auto
      ">Footer</h2>
        </body>
    </html>
  );
}
