import React from 'react';
export const metadata = {
  title: "Timeline",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div className='w-[1600] mx-auto'>
      <h2 className='text-red-500 text-4xl'>Apps page</h2>
    </div>
  );
};

export default page;